# Generated by Django 4.2.2 on 2023-07-03 19:00

from django.db import migrations
import django_enum.fields


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                blank=True, choices=[(0, "pending"), (1, "paid")], default=0, null=True
            ),
        ),
    ]
