# Generated by Django 4.2.2 on 2023-07-04 06:11

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0002_initial"),
        ("payment", "0003_alter_payment_borrowing_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="borrowing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="borrowing.borrowing",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                blank=True, choices=[(1, "payment"), (0, "fine")], default=0, null=True
            ),
        ),
    ]
