# Generated by Django 4.2.2 on 2023-06-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0002_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
